// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Dalton Barraclough
// Ported from t-engine4 game/engines/default/engine/Zone.lua:1020-1166 (newLevel's regenerate loop)
//   and game/modules/tome/data/zones/ruins-kor-pul/zone.lua:41-52 (ROOMER_RUINS_KOR_PUL)
//   and game/modules/tome/data/zones/orc-breeding-pit/zone.lua:24-43 (CAVERN_ORC_BREEDING_PIT)
//   and game/modules/tome/class/Game.lua:948-974, :1140-1144 (keepTrying)
// T-Engine4 (C) 2009-2018 Nicolas Casalini "DarkGod" -- https://te4.org/license

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * A LEVEL: GENERATE, CHECK, AND START AGAIN IF IT IS NOT A LEVEL
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `Zone:newLevel` is where upstream turns a generator's output into something a
 * player can finish. It does not repair a bad map — no corridor is dug to a
 * sealed room after the fact — it discards it and generates another, up to
 * `_max_level_generation_count` times (`engine/Zone.lua:1021`), and a map is bad
 * when:
 *
 *   - the generator asked to be recreated (`level.force_recreate`),
 *   - the up stair cannot reach the down stair, or
 *   - a spot that asks for it (every vault entrance) cannot reach its target.
 *
 * ═══ EACH ATTEMPT IS ITS OWN SEED, SO A RETRY IS STILL DETERMINISTIC ═══
 * Upstream's retries continue one RNG stream. Here attempt `n` draws from
 * `createRng(`${seed}#${n}`)`, so the level a seed makes never depends on how
 * many draws an earlier failed attempt happened to spend, and a failed attempt
 * can be regenerated by itself to see why it failed.
 *
 * ═══ WHAT IS NOT PORTED ═══
 * Entities: `newLevel` also queues vault contents and runs the actor, object and
 * trap generators before its connectivity checks (`engine/Zone.lua:1081-1116`).
 * Population here is `populateDelve`'s job, after the map is final.
 */

import type { TileXY } from '../coords.ts';
import type { AuthoredMap, LitRoom } from '../level.ts';
import { TileCode } from '../protocol.ts';
import { createRng } from '../rng.ts';
import type { Rng } from '../rng.ts';
import { VAULTS_BY_SHAPE } from '../vaults.ts';
import { createBuilding, generate as generateBuilding } from './building.ts';
import type { BuildingData } from './building.ts';
import { createCavern, generate as generateCavern } from './cavern.ts';
import type { CavernData } from './cavern.ts';
import { reachable } from './connectivity.ts';
import { createForest, generate as generateForest } from './forest.ts';
import type { ForestData } from './forest.ts';
import { NIL_TERRAIN, createGenMap } from './genmap.ts';
import type { GenMap, GridKeys, Spot } from './genmap.ts';
import { truthy } from './lua.ts';
import { createMaze, generate as generateMaze } from './maze.ts';
import type { MazeData } from './maze.ts';
import { createOctopus, generate as generateOctopus } from './octopus.ts';
import type { OctopusMapSpec } from './octopus.ts';
import { createRoomer, generate } from './roomer.ts';
import type { RoomerData } from './rooms-loader.ts';
import { createTown, generate as generateTown } from './town.ts';
import type { TownMapSpec } from './town.ts';

/** `_max_level_generation_count` (`engine/Zone.lua:1021`). */
export const MAX_LEVEL_GENERATION_COUNT = 50;

/** A `generator.map` table naming `engine.generator.map.Roomer`. */
export type RoomerMapSpec = { readonly class: 'Roomer' } & RoomerData;

/** A `generator.map` table naming `engine.generator.map.Cavern`. */
export type CavernMapSpec = { readonly class: 'Cavern' } & CavernData;

/** A `generator.map` table naming `engine.generator.map.Forest`. */
export type ForestMapSpec = { readonly class: 'Forest' } & ForestData;

/** A `generator.map` table naming `engine.generator.map.Maze`. */
export type MazeMapSpec = { readonly class: 'Maze' } & MazeData;

/** A `generator.map` table naming `engine.generator.map.Building`. */
export type BuildingMapSpec = { readonly class: 'Building' } & BuildingData;

/** A zone's `generator.map` table, for every generator class ported so far. */
export type MapGeneratorSpec =
  | RoomerMapSpec
  | CavernMapSpec
  | ForestMapSpec
  | TownMapSpec
  | BuildingMapSpec
  | MazeMapSpec
  | OctopusMapSpec;

/** The part of a zone table a level is built from. */
export type LevelSpec<M extends MapGeneratorSpec = MapGeneratorSpec> = {
  readonly width: number;
  readonly height: number;
  readonly map: M;
  /** Skip the up-to-down check, as `no_level_connectivity` does. */
  readonly noLevelConnectivity?: boolean;
};

export type NewLevelResult = {
  readonly map: AuthoredMap;
  /** How many attempts it took, 1-based. */
  readonly attempts: number;
  /**
   * True when every attempt failed. The map is then the LAST attempt, which is
   * what upstream hands back (`engine/Zone.lua:1026-1029`) — a level, just not
   * a certified one.
   */
  readonly failed: boolean;
};

/**
 * Why a generated map is refused, or `null` if it stands
 * (`engine/Zone.lua:1131-1158`).
 */
function connectivityFailure(
  spec: LevelSpec,
  map: GenMap,
  up: TileXY | null,
  down: TileXY | null,
  spots: readonly Spot[],
): string | null {
  if (
    spec.noLevelConnectivity !== true &&
    up !== null &&
    down !== null &&
    (up.x !== down.x || up.y !== down.y) &&
    !reachable(map, up, down)
  ) {
    return 'no way from the entrance to the exit';
  }
  for (const spot of spots) {
    if (!truthy(spot.checkConnectivity)) continue;
    const target =
      spot.checkConnectivity === 'entrance'
        ? up
        : spot.checkConnectivity === 'exit'
          ? down
          : (spot.checkConnectivity as TileXY);
    if (target === null) continue;
    if ((spot.x !== target.x || spot.y !== target.y) && !reachable(map, spot, target)) {
      return `no way from the ${spot.type} spot at ${String(spot.x)},${String(spot.y)}`;
    }
  }
  return null;
}

/** What one generator run hands `newLevel`: upstream's `ux, uy, dx, dy, spots`, or nothing. */
type GeneratorRun = {
  readonly result: {
    readonly up: TileXY | null;
    readonly down: TileXY | null;
    readonly spots: readonly Spot[];
  } | null;
  /** What a roll lights that `map.rooms` does not hold. See `toAuthoredMap`. */
  readonly lit: readonly LitRoom[];
};

/**
 * `self:getGenerator("map", level, level_data.generator.map)` then
 * `generator:generate(lev, old_lev)` (`engine/Zone.lua:1053-1055`): the class
 * the table names, made afresh for this attempt.
 */
function runGenerator(
  spec: MapGeneratorSpec,
  map: GenMap,
  rng: Rng,
  zone: { readonly maxLevel: number },
  level: { forceRecreate: string | null },
  lev: number,
  oldLev: number,
): GeneratorRun {
  switch (spec.class) {
    case 'Roomer':
      return { result: generate(createRoomer(map, spec, rng, zone, level), lev, oldLev), lit: [] };
    case 'Cavern':
      return {
        result: generateCavern(createCavern(map, spec, rng, zone, level), lev, oldLev),
        lit: [],
      };
    case 'Forest':
      return {
        result: generateForest(createForest(map, spec, rng, zone, level), lev, oldLev),
        lit: [],
      };
    case 'Town':
      return {
        result: generateTown(createTown(map, spec, rng, zone, level), lev, oldLev),
        lit: [],
      };
    case 'Maze':
      return {
        result: generateMaze(createMaze(map, spec, rng, zone, level), lev, oldLev),
        lit: [],
      };
    case 'Octopus':
      return {
        result: generateOctopus(createOctopus(map, spec, rng, zone, level), lev, oldLev),
        lit: [],
      };
    case 'Building': {
      const gen = createBuilding(map, spec, rng, zone, level);
      const result = generateBuilding(gen, lev, oldLev);
      // A BUILDING IS LIT ON ITS OWN ROLL, and it is not a room: `building`
      // rolls `lite_room_chance or 70` and lights the floor it wrote, inside
      // its walls (`engine/generator/map/Building.lua:104`, `:114-116`) — and
      // only that floor, so a vault inside one stays dark.
      const lit = gen.buildings.map((b) => ({
        x0: b.x1 + 1,
        y0: b.y1 + 1,
        x1: b.x2 - 1,
        y1: b.y2 - 1,
        cells: b.floored,
      }));
      return { result, lit };
    }
  }
}

/**
 * `Zone:newLevel(level_data, lev, old_lev)` (`engine/Zone.lua:1023-1166`), for
 * the map alone.
 */
export function newLevel(
  spec: LevelSpec,
  seed: string,
  opts: { readonly level: number; readonly maxLevel: number; readonly oldLevel?: number },
): NewLevelResult {
  let last: AuthoredMap | null = null;
  for (let attempt = 1; attempt <= MAX_LEVEL_GENERATION_COUNT; attempt += 1) {
    const rng = createRng(`${seed}#${String(attempt)}`);
    const map = createGenMap(spec.width, spec.height, spec.map.grid, rng);
    const level = { forceRecreate: null as string | null };
    const zone = { maxLevel: opts.maxLevel };
    const oldLevel = opts.oldLevel ?? opts.level - 1;
    const { result, lit } = runGenerator(spec.map, map, rng, zone, level, opts.level, oldLevel);
    const up = result?.up ?? null;
    const down = result?.down ?? null;
    last = toAuthoredMap(map, up, down, spec.map.grid, lit);
    if (result === null || level.forceRecreate !== null) continue;
    if (connectivityFailure(spec, map, up, down, result.spots) !== null) continue;
    return { map: last, attempts: attempt, failed: false };
  }
  // The loop always runs, so `last` is set; the fallback only satisfies the type.
  return {
    map:
      last ??
      toAuthoredMap(createGenMap(spec.width, spec.height, {}, createRng(seed)), null, null, {}),
    attempts: MAX_LEVEL_GENERATION_COUNT,
    failed: true,
  };
}

/**
 * How many rounds of `MAX_LEVEL_GENERATION_COUNT` attempts `keepTrying` makes
 * before it calls the zone table broken.
 */
export const KEEP_TRYING_ROUNDS = 10;

/**
 * A level `newLevel` certified, or an error.
 *
 * ═══ THE ENGINE HANDS BACK A FAILED LEVEL; THE GAME NEVER PLAYS ONE ═══
 * `Zone:newLevel` returns its last attempt after fifty failures, and says the
 * caller must check (`engine/Zone.lua:1023-1029`). ToME does: it refuses to
 * enter the level and asks the player to stay or to keep trying
 * (`tome/class/Game.lua:1141-1144`), and "keep trying" runs the whole level
 * change again, fifty fresh attempts (`tome/class/Game.lua:972-974`). A server
 * building a floor has nobody to ask, so it keeps trying: round `k` is the seed
 * `${seed}~${k}`, and round 0 is the seed itself, so a level that certifies
 * first time is exactly `newLevel`'s.
 *
 * Measured, no Kor'Pul level has needed a second round in 6,000, so a table
 * that exhausts every round cannot make a level at all and throws.
 */
export function keepTrying(
  spec: LevelSpec,
  seed: string,
  opts: { readonly level: number; readonly maxLevel: number; readonly oldLevel?: number },
): NewLevelResult {
  for (let round = 0; round < KEEP_TRYING_ROUNDS; round += 1) {
    const level = newLevel(spec, round === 0 ? seed : `${seed}~${String(round)}`, opts);
    if (!level.failed) return level;
  }
  throw new Error(
    `keepTrying: ${String(KEEP_TRYING_ROUNDS * MAX_LEVEL_GENERATION_COUNT)} attempts at '${seed}' made no level`,
  );
}

/**
 * The code nil terrain ships as: the wall key — Roomer's `'#'`, else Cavern's
 * `wall` — when it names one code, its first code when it is a table, else WALL.
 * No draw — the map is finished.
 */
function nilTerrainCode(keys: GridKeys): number {
  const wall = keys['#'] ?? keys['wall'];
  if (typeof wall === 'number') return wall;
  if (Array.isArray(wall)) return (wall as readonly number[])[0] ?? TileCode.WALL;
  return TileCode.WALL;
}

/**
 * A generated map as the rest of the game reads one.
 *
 * - `spawns` is `[up]`: upstream's `default_up`, where an arriving party lands.
 * - `down` is where the generator put the down stair; realms decides whether
 *   the floor has one.
 * - `rooms` is the rectangle, walls included, of every placed room a lit roll
 *   lights — all but a lesser vault, whose generator never reads it
 *   (`rooms/lesser_vault.lua:90`) — then `lit`, what a generator lights on a
 *   roll of its own outside the room pool (a Building's buildings, cell by
 *   cell). `shared/light.ts` rolls each one again, on the world's stream, at
 *   the same chance.
 * - `vaults` is every placed room that holds something, in placement order, at
 *   its drawing: a lesser vault's apron is not part of it.
 * - Nil terrain becomes the wall key's code.
 */
export function toAuthoredMap(
  map: GenMap,
  up: TileXY | null,
  down: TileXY | null,
  keys: GridKeys,
  lit: readonly LitRoom[] = [],
): AuthoredMap {
  const nil = nilTerrainCode(keys);
  const tiles: number[] = Array.from(map.tiles, (code) => (code === NIL_TERRAIN ? nil : code));
  const rooms: LitRoom[] = [
    ...map.rooms.flatMap((r) =>
      r.room.ignoresLite === true
        ? []
        : [{ x0: r.x, y0: r.y, x1: r.x + r.room.w - 1, y1: r.y + r.room.h - 1 }],
    ),
    ...lit,
  ];
  const vaults = map.rooms.flatMap((r) =>
    r.room.vault === undefined
      ? []
      : [
          {
            id: r.room.vault.id,
            at: { x: r.x + (r.room.vault.inset ?? 0), y: r.y + (r.room.vault.inset ?? 0) },
            turn: r.room.vault.turn,
            w: r.room.vault.w,
            h: r.room.vault.h,
          },
        ],
  );
  return {
    view: { w: map.w, h: map.h, tiles },
    spawns: up === null ? [] : [up],
    ...(down === null ? {} : { down }),
    sites: new Map(),
    rooms,
    vaults,
  };
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * THE KOR'PUL LEVEL — the first zone a ToME character clears
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `data/zones/ruins-kor-pul/zone.lua:41-52`, as a delve: 50x50, ten rooms from
 * `random_room` with a 5-weighted `money_vault` and an 8-weighted `lesser_vault`,
 * every room lit, and upstream's defaults for everything else (`tunnel_change`
 * 30, `tunnel_random` 10, `door_chance` 50).
 *
 * TWO CHANGES, BOTH ABOUT WHERE THIS RUNS:
 * - `lesser_vaults_list` names four upstream vaults; the pool here is the works
 *   rooms from `shared/vaults.ts`, the ground this analogue stands in for.
 * - `forceLastStair`: upstream's last Kor'Pul floor is a static map, so its
 *   Roomer floors always have a level below. Ours computes a down stair on
 *   every floor and lets the realm decide whether to use it.
 */
export const ROOMER_RUINS_KOR_PUL: LevelSpec<RoomerMapSpec> = {
  width: 50,
  height: 50,
  map: {
    class: 'Roomer',
    nbRooms: 10,
    rooms: ['random_room', ['money_vault', 5], ['lesser_vault', 8]],
    lesserVaultsList: (VAULTS_BY_SHAPE['works'] ?? []).map((v) => v.id),
    liteRoomChance: 100,
    forceLastStair: true,
    grid: {
      '.': TileCode.FLOOR,
      '#': TileCode.WALL,
      up: TileCode.FLOOR,
      down: TileCode.FLOOR,
      door: TileCode.DOOR,
    },
  },
};

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * THE ORC BREEDING PITS — a cave level the way ToME digs one
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `data/zones/orc-breeding-pit/zone.lua:24-43`: 50x50, three levels, NOT lit
 * (`all_lited` is commented out, `:30`), and `engine.generator.map.Cavern` at
 * `zoom = 23` with `min_floor = 900` — a close-grained cave that must keep at
 * least 36% of the map as one connected region. Everything else is Cavern's
 * default: simplex noise, no rooms, no doors. Its level 1 is a static map and
 * its level 3 a 15x15 den (`:73-84`); this is the table levels 2 onward use.
 *
 * ═══ MEASURED ═══
 * Over 5,000 attempts at this table, 58.3% of fresh noise fields had no region
 * of 900 cells, so an attempt started over 1.45 times on average and at most 16
 * times (`CAVERN_MAX_REBUILDS` is 200), and no attempt was refused. The biggest
 * region ran from 196 to 1,249 cells, median 844. About 1 ms a level, p95 2.6 ms.
 *
 * THE GRIDS: `floor` UNDERGROUND_FLOOR, `wall` UNDERGROUND_TREE, the ladders, and
 * `door` UNDERGROUND_FLOOR — the zone's door is its floor. Here floor and wall
 * are the default codes, the ladders are the floor a stair marker stands on, and
 * the door is the floor, as upstream's is.
 *
 * ONE CHANGE, ABOUT WHERE THIS RUNS: `forceLastStair`. Upstream's `max_level = 3`
 * decides which floor has no ladder down; here the realm decides, so the
 * generator always places one (as `ROOMER_RUINS_KOR_PUL` does).
 */
export const CAVERN_ORC_BREEDING_PIT: LevelSpec<CavernMapSpec> = {
  width: 50,
  height: 50,
  map: {
    class: 'Cavern',
    zoom: 23,
    minFloor: 900,
    forceLastStair: true,
    grid: {
      floor: TileCode.FLOOR,
      wall: TileCode.WALL,
      up: TileCode.FLOOR,
      down: TileCode.FLOOR,
      door: TileCode.FLOOR,
    },
  },
};
