// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Dalton Barraclough
// Ported from t-engine4 game/engines/default/engine/Zone.lua:1020-1166 (newLevel's regenerate loop)
//   and game/modules/tome/data/zones/ruins-kor-pul/zone.lua:41-52 (ROOMER_RUINS_KOR_PUL)
//   and game/modules/tome/class/Game.lua:948-974, :1140-1144 (keepTrying)
// T-Engine4 (C) 2009-2018 Nicolas Casalini "DarkGod" -- https://te4.org/license

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * A LEVEL: GENERATE, CHECK, AND START AGAIN IF IT IS NOT A LEVEL
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `Zone:newLevel` is where upstream turns a generator's output into something a
 * player can finish. It does not repair a bad map — no corridor is dug to a
 * sealed room after the fact — it discards it and generates another, up to
 * `_max_level_generation_count` times (`engine/Zone.lua:1021`), and a map is bad
 * when:
 *
 *   - the generator asked to be recreated (`level.force_recreate`),
 *   - the up stair cannot reach the down stair, or
 *   - a spot that asks for it (every vault entrance) cannot reach its target.
 *
 * ═══ EACH ATTEMPT IS ITS OWN SEED, SO A RETRY IS STILL DETERMINISTIC ═══
 * Upstream's retries continue one RNG stream. Here attempt `n` draws from
 * `createRng(`${seed}#${n}`)`, so the level a seed makes never depends on how
 * many draws an earlier failed attempt happened to spend, and a failed attempt
 * can be regenerated by itself to see why it failed.
 *
 * ═══ WHAT IS NOT PORTED ═══
 * Entities: `newLevel` also queues vault contents and runs the actor, object and
 * trap generators before its connectivity checks (`engine/Zone.lua:1081-1116`).
 * Population here is `populateDelve`'s job, after the map is final.
 */

import type { TileXY } from '../coords.ts';
import type { AuthoredMap, TileRect } from '../level.ts';
import { TileCode } from '../protocol.ts';
import { createRng } from '../rng.ts';
import { VAULTS_BY_SHAPE } from '../vaults.ts';
import { reachable } from './connectivity.ts';
import { NIL_TERRAIN, createGenMap } from './genmap.ts';
import type { GenMap, GridKeys, Spot } from './genmap.ts';
import { truthy } from './lua.ts';
import { createRoomer, generate } from './roomer.ts';
import type { RoomerData } from './rooms-loader.ts';

/** `_max_level_generation_count` (`engine/Zone.lua:1021`). */
export const MAX_LEVEL_GENERATION_COUNT = 50;

/** A zone's `generator.map` table. Roomer is the only class ported so far. */
export type MapGeneratorSpec = { readonly class: 'Roomer' } & RoomerData;

/** The part of a zone table a level is built from. */
export type LevelSpec = {
  readonly width: number;
  readonly height: number;
  readonly map: MapGeneratorSpec;
  /** Skip the up-to-down check, as `no_level_connectivity` does. */
  readonly noLevelConnectivity?: boolean;
};

export type NewLevelResult = {
  readonly map: AuthoredMap;
  /** How many attempts it took, 1-based. */
  readonly attempts: number;
  /**
   * True when every attempt failed. The map is then the LAST attempt, which is
   * what upstream hands back (`engine/Zone.lua:1026-1029`) — a level, just not
   * a certified one.
   */
  readonly failed: boolean;
};

/**
 * Why a generated map is refused, or `null` if it stands
 * (`engine/Zone.lua:1131-1158`).
 */
function connectivityFailure(
  spec: LevelSpec,
  map: GenMap,
  up: TileXY | null,
  down: TileXY | null,
  spots: readonly Spot[],
): string | null {
  if (
    spec.noLevelConnectivity !== true &&
    up !== null &&
    down !== null &&
    (up.x !== down.x || up.y !== down.y) &&
    !reachable(map, up, down)
  ) {
    return 'no way from the entrance to the exit';
  }
  for (const spot of spots) {
    if (!truthy(spot.checkConnectivity)) continue;
    const target =
      spot.checkConnectivity === 'entrance'
        ? up
        : spot.checkConnectivity === 'exit'
          ? down
          : (spot.checkConnectivity as TileXY);
    if (target === null) continue;
    if ((spot.x !== target.x || spot.y !== target.y) && !reachable(map, spot, target)) {
      return `no way from the ${spot.type} spot at ${String(spot.x)},${String(spot.y)}`;
    }
  }
  return null;
}

/**
 * `Zone:newLevel(level_data, lev, old_lev)` (`engine/Zone.lua:1023-1166`), for
 * the map alone.
 */
export function newLevel(
  spec: LevelSpec,
  seed: string,
  opts: { readonly level: number; readonly maxLevel: number; readonly oldLevel?: number },
): NewLevelResult {
  let last: AuthoredMap | null = null;
  for (let attempt = 1; attempt <= MAX_LEVEL_GENERATION_COUNT; attempt += 1) {
    const rng = createRng(`${seed}#${String(attempt)}`);
    const map = createGenMap(spec.width, spec.height, spec.map.grid, rng);
    const level = { forceRecreate: null as string | null };
    const gen = createRoomer(map, spec.map, rng, { maxLevel: opts.maxLevel }, level);
    const result = generate(gen, opts.level, opts.oldLevel ?? opts.level - 1);
    const up = result?.up ?? null;
    const down = result?.down ?? null;
    last = toAuthoredMap(map, up, down, spec.map.grid);
    if (result === null || level.forceRecreate !== null) continue;
    if (connectivityFailure(spec, map, up, down, result.spots) !== null) continue;
    return { map: last, attempts: attempt, failed: false };
  }
  // The loop always runs, so `last` is set; the fallback only satisfies the type.
  return {
    map:
      last ??
      toAuthoredMap(createGenMap(spec.width, spec.height, {}, createRng(seed)), null, null, {}),
    attempts: MAX_LEVEL_GENERATION_COUNT,
    failed: true,
  };
}

/**
 * How many rounds of `MAX_LEVEL_GENERATION_COUNT` attempts `keepTrying` makes
 * before it calls the zone table broken.
 */
export const KEEP_TRYING_ROUNDS = 10;

/**
 * A level `newLevel` certified, or an error.
 *
 * ═══ THE ENGINE HANDS BACK A FAILED LEVEL; THE GAME NEVER PLAYS ONE ═══
 * `Zone:newLevel` returns its last attempt after fifty failures, and says the
 * caller must check (`engine/Zone.lua:1023-1029`). ToME does: it refuses to
 * enter the level and asks the player to stay or to keep trying
 * (`tome/class/Game.lua:1141-1144`), and "keep trying" runs the whole level
 * change again, fifty fresh attempts (`tome/class/Game.lua:972-974`). A server
 * building a floor has nobody to ask, so it keeps trying: round `k` is the seed
 * `${seed}~${k}`, and round 0 is the seed itself, so a level that certifies
 * first time is exactly `newLevel`'s.
 *
 * Measured, no Kor'Pul level has needed a second round in 6,000, so a table
 * that exhausts every round cannot make a level at all and throws.
 */
export function keepTrying(
  spec: LevelSpec,
  seed: string,
  opts: { readonly level: number; readonly maxLevel: number; readonly oldLevel?: number },
): NewLevelResult {
  for (let round = 0; round < KEEP_TRYING_ROUNDS; round += 1) {
    const level = newLevel(spec, round === 0 ? seed : `${seed}~${String(round)}`, opts);
    if (!level.failed) return level;
  }
  throw new Error(
    `keepTrying: ${String(KEEP_TRYING_ROUNDS * MAX_LEVEL_GENERATION_COUNT)} attempts at '${seed}' made no level`,
  );
}

/**
 * The code nil terrain ships as: the `'#'` key's wall when it names one code,
 * its first code when it is a table, else WALL. No draw — the map is finished.
 */
function nilTerrainCode(keys: GridKeys): number {
  const wall = keys['#'];
  if (typeof wall === 'number') return wall;
  if (Array.isArray(wall)) return (wall as readonly number[])[0] ?? TileCode.WALL;
  return TileCode.WALL;
}

/**
 * A generated map as the rest of the game reads one.
 *
 * - `spawns` is `[up]`: upstream's `default_up`, where an arriving party lands.
 * - `down` is where the generator put the down stair; realms decides whether
 *   the floor has one.
 * - `rooms` is the rectangle, walls included, of every placed room a lit roll
 *   lights — all but a lesser vault, whose generator never reads it
 *   (`rooms/lesser_vault.lua:90`).
 * - `vaults` is every placed room that holds something, in placement order, at
 *   its drawing: a lesser vault's apron is not part of it.
 * - Nil terrain becomes the `'#'` wall.
 */
export function toAuthoredMap(
  map: GenMap,
  up: TileXY | null,
  down: TileXY | null,
  keys: GridKeys,
): AuthoredMap {
  const nil = nilTerrainCode(keys);
  const tiles: number[] = Array.from(map.tiles, (code) => (code === NIL_TERRAIN ? nil : code));
  const rooms: TileRect[] = map.rooms.flatMap((r) =>
    r.room.ignoresLite === true
      ? []
      : [{ x0: r.x, y0: r.y, x1: r.x + r.room.w - 1, y1: r.y + r.room.h - 1 }],
  );
  const vaults = map.rooms.flatMap((r) =>
    r.room.vault === undefined
      ? []
      : [
          {
            id: r.room.vault.id,
            at: { x: r.x + (r.room.vault.inset ?? 0), y: r.y + (r.room.vault.inset ?? 0) },
            turn: r.room.vault.turn,
            w: r.room.vault.w,
            h: r.room.vault.h,
          },
        ],
  );
  return {
    view: { w: map.w, h: map.h, tiles },
    spawns: up === null ? [] : [up],
    ...(down === null ? {} : { down }),
    sites: new Map(),
    rooms,
    vaults,
  };
}

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * THE KOR'PUL LEVEL — the first zone a ToME character clears
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * `data/zones/ruins-kor-pul/zone.lua:41-52`, as a delve: 50x50, ten rooms from
 * `random_room` with a 5-weighted `money_vault` and an 8-weighted `lesser_vault`,
 * every room lit, and upstream's defaults for everything else (`tunnel_change`
 * 30, `tunnel_random` 10, `door_chance` 50).
 *
 * TWO CHANGES, BOTH ABOUT WHERE THIS RUNS:
 * - `lesser_vaults_list` names four upstream vaults; the pool here is the works
 *   rooms from `shared/vaults.ts`, the ground this analogue stands in for.
 * - `forceLastStair`: upstream's last Kor'Pul floor is a static map, so its
 *   Roomer floors always have a level below. Ours computes a down stair on
 *   every floor and lets the realm decide whether to use it.
 */
export const ROOMER_RUINS_KOR_PUL: LevelSpec = {
  width: 50,
  height: 50,
  map: {
    class: 'Roomer',
    nbRooms: 10,
    rooms: ['random_room', ['money_vault', 5], ['lesser_vault', 8]],
    lesserVaultsList: (VAULTS_BY_SHAPE['works'] ?? []).map((v) => v.id),
    liteRoomChance: 100,
    forceLastStair: true,
    grid: {
      '.': TileCode.FLOOR,
      '#': TileCode.WALL,
      up: TileCode.FLOOR,
      down: TileCode.FLOOR,
      door: TileCode.DOOR,
    },
  },
};
