/**
 * THE COUNTRY, COUNTED — what each named region is actually made of, and
 * whether there is any reason to walk into it.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHY THIS IS A TOOL
 * ═══════════════════════════════════════════════════════════════════════════
 * The overworld announces twelve regions by name as you cross them — *"You come
 * to the Long Strand."* — and every one of those names is a promise about what
 * is underfoot. Nothing could see whether the map kept them: the tiles are
 * generated by `makeOverworld`, the names live in `ALDERBROOK_REGIONS`, and the
 * two had never been put side by side.
 *
 * Same role as `career.mjs` and `rescue-reach.mjs`: a number that lives in one
 * file, is invisible from every other, and decides whether something a player
 * reads is true.
 *
 * The ANSWER, the day this was written, was that the map keeps all of them —
 * the Kettle Range is 37% mountain, the Saintswood 36% trees, the Long Strand
 * 16% shore. `test/shared/overworld.test.ts` now holds the promises that are
 * unambiguous, so this tool is for looking, and that test is for guarding.
 *
 * Usage:  node tools/world.mjs
 */
import { ALDERBROOK_REGIONS, canWalk, makeOverworld } from '../src/shared/level.ts';
import { SITES } from '../src/server/world/realms.ts';
import { TileCode } from '../src/shared/protocol.ts';

const NAME = new Map(Object.entries(TileCode).map(([k, v]) => [v, k]));
const map = makeOverworld();
const lvl = map.view;

const regionOf = (x, y) =>
  ALDERBROOK_REGIONS.find((r) => x >= r.x0 && x <= r.x1 && y >= r.y0 && y <= r.y1)?.name ?? null;

console.log('──── WHAT THE WHOLE MAP IS MADE OF');
console.log('');
const whole = new Map();
for (const t of lvl.tiles) whole.set(t, (whole.get(t) ?? 0) + 1);
for (const [code, n] of [...whole].sort((a, b) => b[1] - a[1])) {
  const pct = ((n / lvl.tiles.length) * 100).toFixed(1);
  console.log(`  ${String(NAME.get(code) ?? code).padEnd(14)} ${String(n).padStart(6)}  ${pct}%`);
}

let walkable = 0;
for (let y = 0; y < lvl.h; y += 1) {
  for (let x = 0; x < lvl.w; x += 1) if (canWalk(lvl, x, y)) walkable += 1;
}
console.log('');
console.log(`  ${lvl.w}x${lvl.h}, ${walkable} of ${lvl.w * lvl.h} cells walkable`);

console.log('');
console.log('──── AND WHAT EACH NAMED REGION IS MADE OF');
console.log('');

const reasons = new Map(ALDERBROOK_REGIONS.map((r) => [r.name, []]));
for (const [key, id] of map.sites) {
  const [x, y] = String(key).split(',').map(Number);
  const where = regionOf(x, y);
  if (where === null) continue;
  const def = SITES.get(id);
  reasons
    .get(where)
    .push(
      `${def?.name ?? id}${def?.kind === 'common' ? ' [town]' : ''}${def?.hidden ? ' [hidden]' : ''}`,
    );
}

console.log('  region                   walkable   what it is made of');
for (const r of ALDERBROOK_REGIONS) {
  const seen = new Map();
  let cells = 0;
  let walk = 0;
  for (let y = r.y0; y <= r.y1; y += 1) {
    for (let x = r.x0; x <= r.x1; x += 1) {
      if (x < 0 || y < 0 || x >= lvl.w || y >= lvl.h) continue;
      seen.set(lvl.tiles[y * lvl.w + x], (seen.get(lvl.tiles[y * lvl.w + x]) ?? 0) + 1);
      cells += 1;
      if (canWalk(lvl, x, y)) walk += 1;
    }
  }
  const top = [...seen]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 4)
    .map(([c, n]) => `${NAME.get(c) ?? c} ${((n / cells) * 100).toFixed(0)}%`)
    .join(', ');
  console.log(
    `  ${r.name.padEnd(24)} ${String(walk).padStart(5)}/${String(cells).padEnd(5)} ${top}`,
  );
}

console.log('');
console.log('──── AND WHETHER THERE IS ANY REASON TO GO THERE');
console.log('');
for (const r of ALDERBROOK_REGIONS) {
  const list = reasons.get(r.name) ?? [];
  console.log(`  ${r.name.padEnd(24)} ${list.length === 0 ? '— nothing —' : list.join(', ')}`);
}
const bare = ALDERBROOK_REGIONS.filter((r) => (reasons.get(r.name) ?? []).length === 0);
console.log('');
console.log(
  `  ${String(bare.length)} of ${String(ALDERBROOK_REGIONS.length)} hold nothing to walk to: ${bare.map((r) => r.name).join(', ')}`,
);
console.log('  Both are edges rather than empty rooms — the Drowned Coast is 7% walkable');
console.log('  (water and the map border), and Ashwick Reach is the approach to Ashwick,');
console.log('  which is what crossing it is told to you FOR.');
