/**
 * THE COUNTRY, COUNTED — what each named region is actually made of, and
 * whether there is any reason to walk into it.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHY THIS IS A TOOL
 * ═══════════════════════════════════════════════════════════════════════════
 * The overworld announces twelve regions by name as you cross them — *"You come
 * to the Long Strand."* — and every one of those names is a promise about what
 * is underfoot. Nothing could see whether the map kept them: the tiles are
 * generated by `makeOverworld`, the names live in `ALDERBROOK_REGIONS`, and the
 * two had never been put side by side.
 *
 * Same role as `career.mjs` and `rescue-reach.mjs`: a number that lives in one
 * file, is invisible from every other, and decides whether something a player
 * reads is true.
 *
 * The ANSWER, the day this was written, was that the map keeps all of them —
 * the Kettle Range is 37% mountain, the Saintswood 36% trees, the Long Strand
 * 16% shore. `test/shared/overworld.test.ts` now holds the promises that are
 * unambiguous, so this tool is for looking, and that test is for guarding.
 *
 * Usage:  node tools/world.mjs
 */
import { ALDERBROOK_REGIONS, canWalk, makeOverworld, regionAt } from '../src/shared/level.ts';
import { SITES } from '../src/server/world/realms.ts';
import { TileCode } from '../src/shared/protocol.ts';

const NAME = new Map(Object.entries(TileCode).map(([k, v]) => [v, k]));
const map = makeOverworld();
const lvl = map.view;

/**
 * WHICH REGION A TILE IS IN — THE GAME'S OWN ANSWER, NOT A SECOND ONE.
 *
 * This read `x >= r.x0 && x <= r.x1 && ...` against `ALDERBROOK_REGIONS`, and a
 * `Region` HAS NO SUCH FIELDS. It is `{ name, x, y }` — a LABEL POINT, and the
 * ground is decided by `ALDERBROOK_REGION_ROWS`, a painted char grid that
 * `regionAt` reads. So every comparison was against `undefined`, every loop over
 * `y0..y1` ran zero times, and the probe printed a full table of `0/0` and
 * "12 of 12 hold nothing to walk to" about a map with 8,346 walkable cells.
 *
 * It was not a boundary case: the ENTIRE measurement was dead, and it read as a
 * content finding. A conclusion drawn from a table of zeros is the worst thing a
 * probe can produce, because the zeros look like data.
 *
 * `regionAt` returns `'the moor'` for unpainted ground, which is a real answer
 * and not a region in the list — so it is filtered rather than counted.
 */
const regionOf = (x, y) => {
  const name = regionAt(x, y);
  return name === 'the moor' ? null : name;
};

console.log('──── WHAT THE WHOLE MAP IS MADE OF');
console.log('');
const whole = new Map();
for (const t of lvl.tiles) whole.set(t, (whole.get(t) ?? 0) + 1);
for (const [code, n] of [...whole].sort((a, b) => b[1] - a[1])) {
  const pct = ((n / lvl.tiles.length) * 100).toFixed(1);
  console.log(`  ${String(NAME.get(code) ?? code).padEnd(14)} ${String(n).padStart(6)}  ${pct}%`);
}

let walkable = 0;
for (let y = 0; y < lvl.h; y += 1) {
  for (let x = 0; x < lvl.w; x += 1) if (canWalk(lvl, x, y)) walkable += 1;
}
console.log('');
console.log(`  ${lvl.w}x${lvl.h}, ${walkable} of ${lvl.w * lvl.h} cells walkable`);

console.log('');
console.log('──── AND WHAT EACH NAMED REGION IS MADE OF');
console.log('');

const reasons = new Map(ALDERBROOK_REGIONS.map((r) => [r.name, []]));
for (const [key, id] of map.sites) {
  const [x, y] = String(key).split(',').map(Number);
  const where = regionOf(x, y);
  if (where === null) continue;
  const def = SITES.get(id);
  reasons
    .get(where)
    .push(
      `${def?.name ?? id}${def?.kind === 'common' ? ' [town]' : ''}${def?.hidden ? ' [hidden]' : ''}`,
    );
}

/** What the table below measured, so the closing note reads rows rather than a literal. */
const regionStats = new Map();
console.log('  region                   walkable   what it is made of');
for (const r of ALDERBROOK_REGIONS) {
  const seen = new Map();
  let cells = 0;
  let walk = 0;
  // THE WHOLE MAP, ASKING EACH CELL WHICH REGION IT IS IN. A region is a painted
  // shape rather than a rectangle, so there is no box to walk.
  for (let y = 0; y < lvl.h; y += 1) {
    for (let x = 0; x < lvl.w; x += 1) {
      if (regionOf(x, y) !== r.name) continue;
      seen.set(lvl.tiles[y * lvl.w + x], (seen.get(lvl.tiles[y * lvl.w + x]) ?? 0) + 1);
      cells += 1;
      if (canWalk(lvl, x, y)) walk += 1;
    }
  }
  regionStats.set(r.name, { walk, cells });
  const top = [...seen]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 4)
    .map(([c, n]) => `${NAME.get(c) ?? c} ${((n / cells) * 100).toFixed(0)}%`)
    .join(', ');
  console.log(
    `  ${r.name.padEnd(24)} ${String(walk).padStart(5)}/${String(cells).padEnd(5)} ${top}`,
  );
}

console.log('');
console.log('──── AND WHETHER THERE IS ANY REASON TO GO THERE');
console.log('');
for (const r of ALDERBROOK_REGIONS) {
  const list = reasons.get(r.name) ?? [];
  console.log(`  ${r.name.padEnd(24)} ${list.length === 0 ? '— nothing —' : list.join(', ')}`);
}
const bare = ALDERBROOK_REGIONS.filter((r) => (reasons.get(r.name) ?? []).length === 0);
console.log('');
console.log(
  `  ${String(bare.length)} of ${String(ALDERBROOK_REGIONS.length)} hold nothing to walk to: ${bare.map((r) => r.name).join(', ')}`,
);
/**
 * THE LINE THAT USED TO SIT HERE WAS THE CLUE, NOT THE STALE PART.
 *
 * It read: *"Both are edges rather than empty rooms — the Drowned Coast is 7%
 * walkable (water and the map border), and Ashwick Reach is the approach to
 * Ashwick"*. When `regionOf` broke, the count above became 12 and this sentence
 * went on saying "Both" underneath it — which is exactly how the breakage was
 * spotted. Rewriting the prose to match 12 would have destroyed the evidence and
 * shipped a table of zeros as a content finding.
 *
 * SO IT IS DERIVED NOW, and cannot drift from the rows again: Ashwick Reach has
 * held a town for some time and was still being named here as bare, and the
 * Drowned Coast's 7% is 0.02% on the map as it stands.
 */
for (const r of bare) {
  const stat = regionStats.get(r.name);
  const pct = stat === undefined || stat.cells === 0 ? 0 : (stat.walk / stat.cells) * 100;
  console.log(
    pct < 5
      ? `  ${r.name} is an EDGE rather than an empty room — ${pct.toFixed(1)}% of it can be walked on at all.`
      : `  ${r.name} is ${pct.toFixed(0)}% walkable and holds nothing: real ground with no reason to cross it.`,
  );
}
